### ISSUE TITLE
TypeError: makedirs() got an unexpected keyword argument 'exists_ok' on python2.7

### ISSUE THREAD

**Issue by Chanpreet08** [ozanonurtek/flask-now#4]
I was unable to create the flask initial project with MVC architecture in python 2.7 environment. Below is the stack trace for the same. The library is working fine with simple mode.

(venv) ➜  mastering-flask flask-now -mvc
Creating extensionless flask app with mvc architecture pattern.
Installing requirements...
Freezing requirements...
Traceback (most recent call last):
  File "/usr/local/bin/flask-now", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/flask_now/now.py", line 12, in main
    build()
  File "/usr/local/lib/python2.7/site-packages/flask_now/now.py", line 9, in build
    architect.build()
  File "/usr/local/lib/python2.7/site-packages/flask_now/architect.py", line 109, in build
    self.__identify()
  File "/usr/local/lib/python2.7/site-packages/flask_now/architect.py", line 14, in __identify
    self.__create_mvc_architecture()
  File "/usr/local/lib/python2.7/site-packages/flask_now/architect.py", line 20, in __create_mvc_architecture
    self.__create_mvc_app()
  File "/usr/local/lib/python2.7/site-packages/flask_now/architect.py", line 44, in __create_mvc_app
    self.__create_config_file(filename="project/config.py")
  File "/usr/local/lib/python2.7/site-packages/flask_now/architect.py", line 30, in __create_config_file
    os.makedirs(os.path.dirname(filename), exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

**Comment by ozanonurtek** [comment]
Flask-Now v0.2.1 available. Only supports python3 and higher.
